-- Table: FACT_INDICATOR
CREATE TABLE FACT_INDICATOR (
    Temporal_UID bigint  NOT NULL,
    Location_UID bigint  NOT NULL,
    Indicator_UID bigint  NOT NULL,
    Indicator_Value real  NOT NULL,
    Import_UID bigint  NOT NULL,
    CONSTRAINT FACT_INDICATOR_PK PRIMARY KEY (Indicator_UID,Location_UID,Temporal_UID)
);

-- Reference: FACT_TABLE_METRIC_DETAILS (table: FACT_INDICATOR)
ALTER TABLE FACT_INDICATOR ADD CONSTRAINT FACT_TABLE_METRIC_DETAILS
    FOREIGN KEY (Indicator_UID)
    REFERENCES VAR_INDICATOR (Indicator_UID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;

-- Reference: FACT_TABLE_TEMPORAL (table: FACT_INDICATOR)
ALTER TABLE FACT_INDICATOR ADD CONSTRAINT FACT_TABLE_TEMPORAL
    FOREIGN KEY (Temporal_UID)
    REFERENCES DIM_TEMPORAL (Temporal_UID)  
    NOT DEFERRABLE 
    INITIALLY IMMEDIATE
;
