-- Table: VAR_CATEGORY
CREATE TABLE VAR_CATEGORY (
    Category_UID bigserial  PRIMARY KEY,
    Category_Name varchar(256)  NOT NULL,
    CONSTRAINT VAR_CATEGORY_NAME_UK UNIQUE (Category_Name) NOT DEFERRABLE  INITIALLY IMMEDIATE
);